name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Ensures the workflow runs on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Ensure this matches your runtime.txt

    - name: Install dependencies
      run: |
        cd Part1_Local_and_Heroku_Deployment  # Change to the directory where your code is located
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "nyhouseprice"
        heroku_email: "leticiagenao403@gmail.com"
        usedocker: false
        appdir: "Part1_Local_and_Heroku_Deployment"  # Specify the directory
